name: Fo
favicon: null
layout_spectrum: 0.30702
typography_spectrum: 0.52632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3275d8'
    - '#cbffff'
    - '#e0b5c3'
    - '#291df6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
